services:
  - type: web
    name: budget-buddy
    env: docker
    branch: main
    dockerfilePath: Dockerfile
    startCommand: sh -c "php artisan serve --host=0.0.0.0 --port $PORT"
    healthCheckPath: /
    deployCommand: |
      php artisan migrate --force