name: Run Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite
        coverage: xdebug
        tools: composer:v2
    
    - name: Copy .env
      run: cp .env.example .env
    
    - name: Install Composer Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    
    - name: Generate Key
      run: php artisan key:generate
    
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    
    - name: Run PHP Tests
      run: composer test

  javascript-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install NPM Dependencies
      run: npm ci
    
    - name: Build Frontend Assets
      run: npm run build
    
    - name: Run JavaScript Tests
      run: npm test

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [laravel-tests, javascript-tests]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite
        coverage: xdebug
        tools: composer:v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Copy .env
      run: cp .env.example .env
    
    - name: Install Composer Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    
    - name: Install NPM Dependencies
      run: npm ci
    
    - name: Generate Key
      run: php artisan key:generate
    
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    
    - name: Build Frontend Assets
      run: npm run build
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Start Laravel Server
      run: php artisan serve --port=8000 &
    
    - name: Wait for Server
      run: sleep 5
    
    - name: Run E2E Tests
      run: npx playwright test
